// Auto-generated by tools/build_zh_font.py -- DO NOT EDIT.
// 16x16 Chinese poetry glyph atlas, indexed by token id.
// Regenerate whenever tools/vocab.json changes.
#pragma once
#include <stdint.h>

#define ZH_FONT_COUNT 2048

extern const uint8_t zh_font_16x16[ZH_FONT_COUNT][32];
